language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops4labsitalovarela
  api:
    key:
      secure: PQdcADU8z5N5zgJ3BZC031yFHNleIpZowFjbrxz7wquQSIlOwZ417KKKM0ZJ4ER+frDLaZQ8j7CqOahqLttUj/056m8JINafOI0CYn66UsSATRHAkZSOaqIVJw8OsYM2Snu95UFWpCjGr1TBuQB44Vd3WK3udKclVc64zM60bBIH5xH2OyWK8moTn8Qr21Fl2vwSSE9niPczgnW95X7BU/nxNO2PgM0thypwxGNwGGctK8D3LSPsRRiGZkneSWyUrKqk4Qxn8mzhDVZ8O3ld+JXEdYn7DDTm3Ypwu3arjgIS4Rq9+T3RHNdNL3zow2JEVdBsV1l+nqqF+ORvqWQkYTz+r0bLcnlQfcUhli6KQnP0VH1doYNOi/jZRry2JOTOOxD9WToRL9TJMBxUWNPAQCN9ZbtxtranCFMITo+WmRJFk6JMwJV9bT0y8HFCwM5JYwJwAQlp+ByQrb95eYKab61eDTlxD+aPSJ2nQYI+6AVetrmlihiqkylM1KMey7IgEYRVmNJCh/A5R77rWguVIA0iRZjo6elGGj4oURoVhkIdl869naSe4yujaMbd/C5hfuyZhnOnknATu59jVXHGWLaTgzY4ZAedVLeCB2pJWgR3i19rabd3Rgzz0uH6OMuqHItraYa+KJuolS8wYgIXMJ+PQUU4r1RqEFY8KemV16k=
  api_key:
    secure: mZjBsDIa03iXWzObhB0qJvK3MEadlnPqev1cCkYg02qhznFMm7KmYCShB0LAqdMRrtusxAwYEAX87jDHN89ZgP8K8ZMOJChpYYv+CBGsSJOSnadKOhDLn/6Zz39DqQm7RQu3FhZEdJEDfecU6a2nQlwVfNNPv/Lv2ONffDJ8L707iXKPaMFTAFBVuysgb9SUxOwAYO3yoDmN6Q6sjQvfcpEJ2MQtCeiFXmHfVmnSW8WbEnc8/Eq9lha+UCqmbZwSTAn0rxMO2j4+Oalih/BVcrDxQfMw42VltpUwpK84gR03dHc6NdczCFDB1oYvu/PDENp7ZVgq4ic+IrEFnBczv+73GBsS0Shr1TwJtrCVZbD8MS0vpfjyUafvTpbIn3bjx9R9p06bmRefVw6DYKshnsg0hj6pxrpbRE32JWgiF9vTriKGzNCHsK7/nUCieEXdiihhSzjNIBfVzUvVbanDJns60/SNzEDhAtg0zsE/oH8qzYqV1yzW1s3cky+S7FQ8uVdr/wyBAHB+QuwN+KuUK3EXGMietFv+RBUlrQHnGTrHLnJRBDPJUBcohQ8j58MUhlWjYpQ4l/5nRv+O7tCiTSrYrK9x0b5lnHlGtLrckhdOYc8P/Xa2YTdN5xorZPR1ipauU7oUTJYnGvOr4Asvnsjr/PElz159qr/WpZ14rY8=
